@genType
let mockMovies: array<AppTypes.media> = [
  {
    id: "1",
    title: "Inception",
    thumbnail: "https://picsum.photos/seed/inception/400/600",
    category: AppTypes.Movie,
    description: "A thief enters dreams to steal secrets.",
    year: 2010,
    duration: "2h 28min",
    rating: 4.8,
  },
  {
    id: "2",
    title: "Stranger Things",
    thumbnail: "https://picsum.photos/seed/stranger/400/600",
    category: AppTypes.TVShow,
    description: "Kids face mysterious forces in their town.",
    year: 2016,
    duration: "4 Seasons",
    rating: 4.7,
  },
  {
    id: "3",
    title: "Planet Earth III",
    thumbnail: "https://picsum.photos/seed/planet/400/600",
    category: AppTypes.Documentary,
    description: "An epic journey through wilderness.",
    year: 2023,
    duration: "8 Episodes",
    rating: 4.9,
  },
  {
    id: "4",
    title: "The Last of Us",
    thumbnail: "https://picsum.photos/seed/lastofus/400/600",
    category: AppTypes.Series,
    description: "Surviving in a post-apocalyptic world.",
    year: 2023,
    duration: "2 Seasons",
    rating: 4.9,
  },
  {
    id: "5",
    title: "Grand Prix F1 Monaco",
    thumbnail: "https://picsum.photos/seed/monaco/400/600",
    category: AppTypes.Live,
    description: "Live race from Monaco.",
    year: 2024,
    duration: "Live",
    rating: 4.6,
  },
  {
    id: "6",
    title: "Interstellar",
    thumbnail: "https://picsum.photos/seed/interstellar/400/600",
    category: AppTypes.Movie,
    description: "Space exploration to save humanity.",
    year: 2014,
    duration: "2h 49min",
    rating: 4.8,
  },
  {
    id: "7",
    title: "Squid Game",
    thumbnail: "https://picsum.photos/seed/squid/400/600",
    category: AppTypes.Series,
    description: "Players risk their lives for a prize.",
    year: 2021,
    duration: "2 Seasons",
    rating: 4.7,
  },
  {
    id: "8",
    title: "Breaking Bad",
    thumbnail: "https://picsum.photos/seed/breaking/400/600",
    category: AppTypes.TVShow,
    description: "A chemistry teacher becomes a drug lord.",
    year: 2008,
    duration: "5 Seasons",
    rating: 4.9,
  },
  {
    id: "9",
    title: "Ocean World",
    thumbnail: "https://picsum.photos/seed/ocean/400/600",
    category: AppTypes.Documentary,
    description: "A dive into the depths of the ocean.",
    year: 2022,
    duration: "6 Episodes",
    rating: 4.5,
  },
  {
    id: "10",
    title: "Oppenheimer",
    thumbnail: "https://picsum.photos/seed/oppenheimer/400/600",
    category: AppTypes.Movie,
    description: "The father of the atomic bomb.",
    year: 2023,
    duration: "3h 00min",
    rating: 4.7,
  },
  {
    id: "11",
    title: "Coldplay — Live World Tour",
    thumbnail: "https://picsum.photos/seed/coldplay/400/600",
    category: AppTypes.Live,
    description: "World tour live concert.",
    year: 2024,
    duration: "Live",
    rating: 4.8,
  },
  {
    id: "12",
    title: "Dune: Part Two",
    thumbnail: "https://picsum.photos/seed/dune2/400/600",
    category: AppTypes.Movie,
    description: "Paul Atreides leads the Fremen revolt.",
    year: 2024,
    duration: "2h 46min",
    rating: 4.8,
  },
]
